<?php

/**
 * @file
 * Contains email_format.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function email_format_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the email_format module.
    case 'help.page.email_format':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Formato de Correo') . '</p>';
      return $output;

    default:
  }
}
